/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com;


import com.ui.WrapLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Chingo
 */
public class CCListGroup extends javax.swing.JPanel {

   

    /**
     * Creates new form CCListGroup
     */
    public CCListGroup() {
        initComponents();
  
        this.setLayout(new WrapLayout());

        
        ImageIcon icon = new ImageIcon("C:\\Users\\Chingo\\Documents\\NetBeansProjects\\Workshop\\CCWorkshop\\character\\images\\kasumi.jpg");
        this.add(new CCListGroupItem(icon, "kasumi"));
        this.add(new CCListGroupItem(icon, "kasumi"));
        this.add(new CCListGroupItem(icon, "kasumi"));
        this.add(new CCListGroupItem(icon, "kasumi"));

        
       
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Group Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
