/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Chingo
 */
public class CCListGroupItem extends javax.swing.JPanel {

    /**
     * Creates new form CCListGroupItem
     */
    public CCListGroupItem() {
        initComponents();
    }

    public CCListGroupItem(ImageIcon imageIcon, String name) {
        initComponents();
        Image image =  imageIcon.getImage()
                .getScaledInstance(itemView.getPreferredSize().width,
                itemView.getPreferredSize().height,
                java.awt.Image.SCALE_SMOOTH);
        
        ImageIcon icon = new ImageIcon(image);
        
        itemView.setIcon(icon);
        itemNameLabel.setText(name);
    }
    
    public void setItemView(Image image) {
        image.getScaledInstance(itemView.getPreferredSize().width,
                itemView.getPreferredSize().height,
                java.awt.Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(image);
        itemView.setIcon(icon);
    }
    
    public void setItemLabel(String name) {
        itemNameLabel.setText(name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemView = new javax.swing.JButton();
        itemNameLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(105, 124));

        itemView.setPreferredSize(new java.awt.Dimension(95, 95));

        itemNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNameLabel.setText("name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(itemNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(itemView, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(itemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JButton itemView;
    // End of variables declaration//GEN-END:variables
}
