/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import com.ui.ScrollablePanel;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author Chingo
 */
public class CCManager extends javax.swing.JFrame {
    /**
     * Creates new form test
     */
    public CCManager() {
        initComponents();
        setLocationRelativeTo(null);

        characterTab.setLayout(new GridLayout());
        characterTab.add(new CCListGroup());
        
        
        
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabMenu = new javax.swing.JTabbedPane();
        characterTab = new com.ui.ScrollablePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        resolutionOption1 = new javax.swing.JMenuItem();
        resolutionOption2 = new javax.swing.JMenuItem();
        resolutionOption3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CCManager");
        setResizable(false);

        tabMenu.setAutoscrolls(true);

        javax.swing.GroupLayout characterTabLayout = new javax.swing.GroupLayout(characterTab);
        characterTab.setLayout(characterTabLayout);
        characterTabLayout.setHorizontalGroup(
            characterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        characterTabLayout.setVerticalGroup(
            characterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        tabMenu.addTab("Character", characterTab);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("view");

        resolutionOption1.setText("800x600");
        resolutionOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolutionOption1ActionPerformed(evt);
            }
        });
        jMenu2.add(resolutionOption1);

        resolutionOption2.setText("500x300");
        resolutionOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolutionOption2ActionPerformed(evt);
            }
        });
        jMenu2.add(resolutionOption2);

        resolutionOption3.setText("FullScreen");
        resolutionOption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolutionOption3ActionPerformed(evt);
            }
        });
        jMenu2.add(resolutionOption3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addComponent(tabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resolutionOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolutionOption1ActionPerformed
        setVisible(false);
        this.setPreferredSize(new Dimension(800,600));
        this.pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }//GEN-LAST:event_resolutionOption1ActionPerformed

    private void resolutionOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolutionOption2ActionPerformed
        setVisible(false);
        setPreferredSize(new Dimension(500,300));
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }//GEN-LAST:event_resolutionOption2ActionPerformed

    private void resolutionOption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolutionOption3ActionPerformed
        setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_resolutionOption3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CCManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CCManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CCManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CCManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CCManager().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ui.ScrollablePanel characterTab;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem resolutionOption1;
    private javax.swing.JMenuItem resolutionOption2;
    private javax.swing.JMenuItem resolutionOption3;
    private javax.swing.JTabbedPane tabMenu;
    // End of variables declaration//GEN-END:variables

    
}
